name: Lint and Type Check

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-version: "3.10"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (incluindo PySpark)
        run: |
          pip install black flake8 mypy pylint pyspark
          
  black:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Black (code formatting)
        run: black --check --diff .

  flake8:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Flake8 (style check)
        run: flake8 .

  mypy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Mypy (type checking)
        run: mypy .

  pylint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Pylint (code analysis)
        run: pylint $(git ls-files '*.py')