name: Python Syntax Check

on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  python_syntax_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências do Python e PySpark
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pyspark

      - name: Verificar sintaxe com Black
        run: black --check .

      - name: Verificar erros com Flake8 (Python e PySpark)
        run: flake8 .

      - name: Teste de importação do PySpark
        run: python -c "import pyspark; print('PySpark importado com sucesso!')"

      - name: Rodar um teste básico do PySpark
        run: |
          python - <<EOF
          from pyspark.sql import SparkSession

          spark = SparkSession.builder.appName("TestSession").getOrCreate()
          df = spark.createDataFrame([(1, "Teste")], ["id", "nome"])
          df.show()
          print("PySpark rodou com sucesso!")
          spark.stop()
          EOF