name: Lint and Type Check

on:
  push:
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Black
        run: pip install black

      - name: Check Black Installation
        run: black --version

      - name: Run Black (code formatting)
        run: black --check --diff .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Flake8
        run: pip install flake8

      - name: Check Flake8 Installation
        run: flake8 --version

      - name: Run Flake8 (style check)
        run: flake8 .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Mypy and PySpark
        run: pip install mypy pyspark

      - name: Check Mypy Installation
        run: mypy --version

      - name: Create Mypy Config
        run: |
          echo "[mypy]" > mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini

      - name: Run Mypy (type checking)
        run: mypy .

  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Pylint and PySpark
        run: pip install pylint pyspark

      - name: Check Pylint Installation
        run: pylint --version

      - name: Run Pylint (code analysis)
        run: pylint $(git ls-files '*.py')
