name: Python Syntax Check

on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Teste Script
        run: python aula_01/main.py

      # - name: Instalar dependências
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install black flake8

      # - name: Verificar sintaxe com Black
      #   run: black --check .

      # - name: Verificar erros com Flake8
      #   run: flake8 .
